apiVersion: v1
kind: Pod
metadata:
  annotations:
    container.seccomp.security.alpha.kubernetes.io/nginx: runtime/default
  labels:
    app: app-alpha
  name: resource-alpha
spec:
  containers:
  - image: nginx
    name: container-alpha
